version: '3.8'
services:
  db:
    image: postgres:12-alpine
    ports:
      - 5433:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - trade_platform/.env
  web:
    build:
      context: trade_platform
      dockerfile: Dockerfile
    volumes:
      - ./trade_platform:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - trade_platform/.env
